
# 组件内部编译

# LOCAL_PATH := $(call my-dir)
LOCAL_PATH := Middlewares/RTOS

# 头文件路径
LOCAL_INCLUDES := $(LOCAL_PATH)/StdIf/Include
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/Config
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/uC-CPU-1.32.01
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/uC-CPU-1.32.01/ARM-Cortex-M/ARMv7-M/GNU
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/uC-LIB-1.39.01
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/uC-OS3-3.08.02/Source
LOCAL_INCLUDES += $(LOCAL_PATH)/Source/UCOSIII/uC-OS3-3.08.02/Ports/ARM-Cortex-M/ARMv7-M/GNU

# 源文件路径
LOCAL_SOURCES_DIRS := $(LOCAL_PATH)/Source/UCOSIII/Config
LOCAL_SOURCES_DIRS += $(LOCAL_PATH)/Source/UCOSIII/uC-LIB-1.39.01
LOCAL_SOURCES_DIRS += $(LOCAL_PATH)/Source/UCOSIII/uC-OS3-3.08.02/Source

# 源文件
LOCAL_C_SOURCES := $(LOCAL_PATH)/Source/UCOSIII/uC-CPU-1.32.01/cpu_core.c
LOCAL_C_SOURCES += $(LOCAL_PATH)/Source/UCOSIII/uC-CPU-1.32.01/ARM-Cortex-M/ARMv7-M/cpu_c.c
LOCAL_C_SOURCES += $(LOCAL_PATH)/Source/UCOSIII/uC-OS3-3.08.02/Ports/ARM-Cortex-M/ARMv7-M/os_cpu_c.c

# 汇编源文件
LOCAL_ASM_SOURCES := $(LOCAL_PATH)/Source/UCOSIII/uC-CPU-1.32.01/ARM-Cortex-M/ARMv7-M/GNU/cpu_a.s
LOCAL_ASM_SOURCES += $(LOCAL_PATH)/Source/UCOSIII/uC-OS3-3.08.02/Ports/ARM-Cortex-M/ARMv7-M/GNU/os_cpu_a.s
